name: Teste de Instalação de Aplicativos

on:
  workflow_dispatch:

jobs:
  test-installation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalação dos aplicativos
        run: |
          chmod +x install_apps.sh
          ./install_apps.sh
