name: Setup Script CI

on:
  workflow_dispatch:

jobs:
  setup-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Run setup.sh
      run: |
        chmod +x ./setup.sh
        ./setup.sh
